# Generated by Django 5.0.1 on 2024-02-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_user_alter_post_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="title",
            field=models.CharField(default=1, max_length=100, verbose_name="Заголовок"),
            preserve_default=False,
        ),
    ]
