# Generated by Django 5.0.1 on 2024-02-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_readstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Заголовок"
            ),
        ),
    ]
