# Generated by Django 4.2.9 on 2024-02-07 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_blog_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="title",
        ),
    ]
