# Generated by Django 5.0.1 on 2024-02-05 21:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
        migrations.CreateModel(
            name="VerifyToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=70, null=True, verbose_name="имя"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="фамилия"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="email",
                    ),
                ),
                ("token", models.PositiveIntegerField(verbose_name="токен")),
                ("uuid", models.UUIDField(default=uuid.uuid4, verbose_name="uuid")),
                (
                    "activation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата деактивации"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verify_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Токен",
                "verbose_name_plural": "Токены",
            },
        ),
    ]
