# Generated by Django 4.2.9 on 2024-02-06 20:57

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_user_email_verifytoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verifytoken",
            name="activation_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата деактивации"
            ),
        ),
        migrations.AlterField(
            model_name="verifytoken",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, unique=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="verifytoken",
            name="token",
            field=models.PositiveIntegerField(verbose_name="Токен"),
        ),
        migrations.AlterField(
            model_name="verifytoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verify_tokens",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="verifytoken",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, verbose_name="Uuid"),
        ),
    ]
