# Generated by Django 4.2.9 on 2024-09-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_alter_verifytoken_activation_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verifytoken",
            name="first_name",
            field=models.CharField(
                blank=True, default=1, max_length=70, verbose_name="имя"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="verifytoken",
            name="last_name",
            field=models.CharField(
                blank=True, default=1, max_length=80, verbose_name="фамилия"
            ),
            preserve_default=False,
        ),
    ]
